site_name: Campus Contributor Docs
site_url: https://osg-htc.org/campus/
repo_name: campus
theme:
  name: material
  logo: assets/OSG_Logo.svg
  favicon: assets/OSG_Logo.png
  features:
    - navigation.sections
    - navigation.path

extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/osg.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

nav:
  - Home:                           index.md
  - OSPool:
    - Integration:                  ospool-integration.md
    - Detailed Requirements:        ospool-requirements.md
    - Metrics:                      ospool-metrics.md
    - Maintenance:                  ospool-maintenance.md
